name: Bicep What-If

on:
  pull_request:
    branches:
      - main

jobs:
  #   build:
  #     runs-on: ubuntu-latest

  generateInputPaths:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate matrix ### Followed this example - https://github.com/Sylius/Sylius/blob/3464e8d0ae6673d9ee1da3d538a6b399cfcb9852/.github/workflows/packages.yml#L48
        working-directory: ${{ github.workspace }}/deploy
        id: set-matrix
        run: |
          echo "::set-output name=matrix::$(find . -mindepth 1 -type d | sed -e 's/.\///' | sort | jq  --raw-input . | jq --slurp . | jq -c .)"
          echo '#################################'
          echo $matrix
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v2

  publishPR:
    needs: generateInputPaths
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJson(needs.generateInputPaths.outputs.matrix) }}

    steps:
      - name: Install Bicep CLI
        run: |
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicep
          sudo mv ./bicep /usr/local/bin/bicep
          bicep --help

      - name: Run Bicep What-If
        id: whatif
        run: |
          bicepOutput=$(bicep build --stdout ./deploy/main.bicep | az deployment group what-if --resource-group myResourceGroup --template-file ./deploy/main.bicep --parameters ./deploy/${{ matrix.path }}/parameters.json)



          bicepOutput="${bicepOutput//'%'/'%25'}"
          bicepOutput="${bicepOutput//$'\n'/'%0A'}"
          bicepOutput="${bicepOutput//$'\r'/'%0D'}"
          echo "::set-output name=bicepOutput::$bicepOutput"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Bicep What-If Results
            ```
            ${{ steps.whatif.outputs.bicepOutput }}
            ```
