name: "Bicep Whatif PR"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  LOCATION: "australiaeast"
  reviewApiUrl: "https://api.contoso.com/reviews"
  reviewApiKey: "12345"

  # ARM_TENANT_ID: "2449bd8c-857f-4212-84c6-819ed04fe712"
  # ARM_SUBSCRIPTION_ID: "b1b7f436-bbc7-43bd-98d9-28fb3b1c8525"
  # ARM_CLIENT_ID_TEST: "61d51774-3018-410f-afb2-c9c9bbf86939"
  # ARM_CLIENT_ID_PROD: "8057493a-4738-4895-b6f8-24d143f17af6"

jobs:
  generateInputPaths:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate matrix ### Followed this example - https://github.com/Sylius/Sylius/blob/3464e8d0ae6673d9ee1da3d538a6b399cfcb9852/.github/workflows/packages.yml#L48
        working-directory: ${{ github.workspace }}/deploy
        id: set-matrix
        run: |
          # echo "::set-output name=matrix::$(find . -mindepth 1 -type d | sed -e 's/.\///' | sort | jq  --raw-input . | jq --slurp . | jq -c .)"
          # echo '#################################'
          # echo $matrix

          echo "matrix=$(find . -mindepth 1 -type d | sed -e 's/.\///' | sort | jq  --raw-input . | jq --slurp . | jq -c .)" >> $GITHUB_OUTPUT
          echo '#################################'
          cat $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  bicep-whatif:
    name: "Bicep Whatif for PR"
    needs: generateInputPaths
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJson(needs.generateInputPaths.outputs.matrix) }}

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Authenticate to Az CLI using OIDC
      - name: "Az CLI login"
        uses: azure/login@v1
        if: matrix.path == 'test'
        with:
          client-id: $var_ARM_CLIENT_ID_TEST #${{ env.ARM_CLIENT_ID_TEST }}
          tenant-id: $var_ARM_TENANT_ID #${{ env.ARM_TENANT_ID }}
          subscription-id: $var_ARM_SUBSCRIPTION_ID #${{ env.ARM_SUBSCRIPTION_ID }}

      - name: "Az CLI login"
        uses: azure/login@v1
        if: matrix.path == 'production'
        with:
          client-id: $var_ARM_CLIENT_ID_TEST #${{ env.ARM_CLIENT_ID_TEST }}
          tenant-id: $var_ARM_TENANT_ID #${{ env.ARM_TENANT_ID }}
          subscription-id: $var_ARM_SUBSCRIPTION_ID #${{ env.ARM_SUBSCRIPTION_ID }}

        # Checks that all Bicep configuration files adhere to a canonical format
      - name: Bicep Lint
        uses: Azure/cli@v1
        with:
          inlineScript: az bicep build --file ${{ github.workspace }}/deploy/main.bicep

      # Validate whether a template is valid at subscription scope
      - name: Bicep Validate
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az deployment group validate \
              --name validate-${{ github.run_id }} \
              --resource-group ToyWebsite${{ matrix.path }} \
              --template-file  ${{ github.workspace }}/deploy/main.bicep \
              --parameters ${{ github.workspace }}/deploy/${{ matrix.path }}/parameters.json \
              --parameters reviewApiUrl=${{ env.reviewApiUrl }} reviewApiKey=${{ env.reviewApiKey }}

      # Perform a security scan of the bicep code using checkov
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          framework: bicep

      # Upload results to GitHub Advanced Security
      - name: Upload SARIF file
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
          category: checkov

      - name: "What-If"
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az deployment group what-if \
              --name whatif-${{ github.run_id }} \
              --resource-group ToyWebsite${{ matrix.path }} \
              --template-file  ${{ github.workspace }}/deploy/main.bicep \
              --parameters ${{ github.workspace }}/deploy/${{ matrix.path }}/parameters.json \
              --parameters reviewApiUrl=${{ env.reviewApiUrl }} reviewApiKey=${{ env.reviewApiKey }} > whatif

        # Create string output of Whatif
      - name: Create String Output
        id: whatif-string
        run: |
          WHATIF=$(cat whatif)

          delimiter="$(openssl rand -hex 8)"
          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
          echo "## Whatif Output --> ${{ matrix.path }} Environment" >> $GITHUB_OUTPUT
          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo "$WHATIF" >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo "</details>" >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT

      # Publish Terraform Plan as task summary
      - name: Publish Whatif to Task Summary
        env:
          SUMMARY: ${{ steps.whatif-string.outputs.summary }}
        run: |
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

      # If this is a PR post the changes
      - name: Push Whatif Output to PR
        if: github.ref != 'refs/heads/main'
        uses: actions/github-script@v6
        env:
          SUMMARY: "${{ steps.whatif-string.outputs.summary }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = `${process.env.SUMMARY}`;
            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
            })
